# Render deployment configuration for Squadbox
services:
  - type: web
    name: squadbox-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: squadbox-db
          property: connectionString
      - key: MONGODB_URI
        fromDatabase:
          name: squadbox-mongodb
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production

databases:
  - name: squadbox-db
    plan: free
    engine: postgresql
  - name: squadbox-mongodb
    plan: free
    engine: mongodb
