#!/bin/bash
# Setup deployment configuration for Squadbox
# Purpose: Configure GitHub secrets and deployment settings
# Last modified: 2025-01-09
# By: AI Assistant
# Completeness: 100/100

echo "🔧 Squadbox Deployment Setup"
echo "============================="

echo "📋 Required GitHub Secrets:"
echo ""
echo "For Vercel deployment, add these secrets to your GitHub repository:"
echo "  - VERCEL_TOKEN: Get from https://vercel.com/account/tokens"
echo "  - VERCEL_ORG_ID: Get from Vercel dashboard"
echo "  - VERCEL_PROJECT_ID: Get from Vercel dashboard"
echo "  - VITE_API_URL: https://squadbox-backend.onrender.com"
echo ""
echo "For Render deployment, add these secrets:"
echo "  - RENDER_API_KEY: Get from https://dashboard.render.com/account/settings"
echo "  - RENDER_SERVICE_ID: Get from your Render service settings"
echo ""
echo "🔗 Setup Instructions:"
echo ""
echo "1. Vercel Setup:"
echo "   - Go to https://vercel.com"
echo "   - Import your GitHub repository"
echo "   - Configure build settings:"
echo "     - Framework: Vite"
echo "     - Build Command: npm run build"
echo "     - Output Directory: dist"
echo "   - Add environment variables:"
echo "     - VITE_API_URL=https://squadbox-backend.onrender.com"
echo ""
echo "2. Render Setup:"
echo "   - Go to https://dashboard.render.com"
echo "   - Create new Web Service"
echo "   - Connect your GitHub repository"
echo "   - Configure settings:"
echo "     - Build Command: pip install -r backend/requirements-production.txt"
echo "     - Start Command: cd backend && python -m uvicorn app:app --host 0.0.0.0 --port \$PORT"
echo "   - Add environment variables:"
echo "     - DATABASE_URL (from Render database)"
echo "     - MONGODB_URI (from Render database)"
echo "     - OPENAI_API_KEY (your OpenAI key)"
echo "     - SECRET_KEY (generate a secure key)"
echo ""
echo "3. GitHub Secrets Setup:"
echo "   - Go to your GitHub repository"
echo "   - Settings > Secrets and variables > Actions"
echo "   - Add all the secrets listed above"
echo ""
echo "4. Test Deployment:"
echo "   - Run: ./deploy-all.sh"
echo "   - Check deployment status in Vercel and Render dashboards"
echo ""
echo "✅ Setup complete! Your deployments will be automatic on git push."
