import React from 'react';
import { Container, Title, Text, Card, List } from '@mantine/core';
import { IconAlertTriangle } from '@tabler/icons-react';

const LiabilityPage = () => (
  <Container size="xl" py="xl">
    <Title
      order={1}
      ta="center"
      style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 12, marginTop: '-10px', marginBottom: 'calc(var(--mantine-spacing-xl) - 10px)' }}
    >
      <IconAlertTriangle size={32} color="var(--mantine-color-brand-6)" />
      Liability Statement
    </Title>

    <Card p="xl" withBorder>
      <Title order={2} mb="sm">Scope</Title>
      <Text c="dimmed" mb="md">
        This Liability Statement applies to your use of the Squadbox platform and any code, files, or artifacts
        generated by it. Capitalized terms have the meanings set out in our Terms of Use.
      </Text>

      <Title order={2} mb="sm">No Warranties</Title>
      <Text c="dimmed" mb="md">
        The Service and Generated Outputs are provided on an “as is” and “as available” basis. To the maximum extent
        permitted by law, Squadbox disclaims all warranties, expressed or implied, including merchantability, fitness
        for a particular purpose, and non‑infringement.
      </Text>

      <Title order={2} mb="sm">Limitation of Liability</Title>
      <List spacing="xs" mb="md">
        <List.Item>Squadbox will not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages.</List.Item>
        <List.Item>We are not liable for loss of profits, revenue, data, use, goodwill, or other intangible losses.</List.Item>
        <List.Item>
          To the extent permitted by law, our aggregate liability for any claim relating to the Service will not exceed
          the amounts you paid to Squadbox in the 3 months preceding the event giving rise to liability.
        </List.Item>
      </List>

      <Title order={2} mb="sm">Your Responsibilities</Title>
      <List spacing="xs" mb="md">
        <List.Item>Evaluate and test Generated Outputs prior to production use.</List.Item>
        <List.Item>Maintain appropriate backups and disaster‑recovery plans.</List.Item>
        <List.Item>Ensure compliance with laws, third‑party licenses, and security standards.</List.Item>
      </List>

      <Title order={2} mb="sm">Indemnification</Title>
      <Text c="dimmed" mb="md">
        You agree to indemnify and hold harmless Squadbox and its affiliates against claims arising from your use of the
        Service or Generated Outputs, breach of the Terms, or violation of applicable laws.
      </Text>

      <Title order={2} mb="sm">Updates</Title>
      <Text c="dimmed">We may update this statement from time to time. Material changes will be announced on this page.</Text>
    </Card>
  </Container>
);

export default LiabilityPage;


